name: example
description: Example project for fcnui cli
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/shoh-dev/flutter_cn_ui
homepage: https://fcnui.shoh.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  fcnui:
    path: ../
  fcnui_base:
    path: ../../fcnui_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg