name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  cli: cli.dart