name: fcnui
description: The flutter_cn_ui CLI (Command-Line Interface) tool.
version: 1.0.0
repository: https://github.com/shoh-dev/flutter_cn_ui
homepage: https://shoh.dev

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  mockito: ^5.4.4
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  fcnui: fcnui.dart