name: fcnui_base
description: "Base package for fcnui applications. Contains common code for all fcnui applications."
version: 1.0.2
repository: https://github.com/shoh-dev/flutter_cn_ui
homepage: https://fcnui.shoh.dev
documentation: https://fcnui.shoh.dev/docs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  flex_color_scheme: ^7.3.1
  equatable: ^2.0.5
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
#  assets:
#      - assets/fonts/
#  fonts:
#    - family: InterRegular
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf

